### ISSUE TITLE
Can't login after new deployment

### ISSUE THREAD

**Issue by Nuruddinjr** [gdg-x/aura-admin#53]
Just deployed a new copy of Aura and admin projects, followed the documentation and everything went smoothly.
On the Authentication part, I created two users, enabled Email authentication, but after deployment when I try to log in it gives me the following error:

`Alert Error: There is no user record corresponding to this identifier. The user may have been deleted.` 

What might be the problem?

**Comment by bharatagsrwal** [comment]
Hey @Nuruddinjr, Sorry for the delay,

please check your firebase.js file in the config folder of aura-admin, please check it and be sure to have your own configs.
also go to https://console.firebase.google.com/ and in authentication tab and then in signin-methods and enable email 
![image](https://user-images.githubusercontent.com/43988371/93249527-11e85e00-f7af-11ea-8a73-35157737da99.png)
and after that add an cutom user for the very first time, and be ensure that there is only one user which you created just now.

Regards
Bharat Agarwal

**Comment by Nuruddinjr** [comment]
@bharatagsrwal I tried this, but no success

**Comment by bharatagsrwal** [comment]
Hey @Nuruddinjr, if it resolves your issue, then please feel free to close the issue, and if still facing an issue then please let us know.
