### ISSUE TITLE
Node.js 8 has been deprecated

### ISSUE THREAD

**Issue by Trilokia** [gdg-x/aura-admin#65]
Node.js 8 runtime was disabled in the Firebase CLI. Please update it to Node.js 10
From Mar 15, 2021, Firebase no longer supports the executions of existing Node.js 8 functions
![Image of Firebase](https://preview.redd.it/df0i0smiw6051.png?width=608&format=png&auto=webp&s=9e9b8a61a5c6ba0cbeecb592c32f009949781f2a)

**Comment by bharatagsrwal** [comment]
Tracking https://github.com/gdg-x/aura-admin/issues/67

**Comment by vrijraj** [comment]
Fixed in v3.5.0 merged in `master` branch
