### ISSUE TITLE
Need to remove dependencies of Cloud Function

### ISSUE THREAD

**Issue by agarwalbharat** [gdg-x/aura-admin#67]
We need to remove the dependencies of the Firebase Cloud Function as they use Node 10 and to run that, we must have a Blaze plan of Firebase... as mentioned in #65

**Comment by bharatagsrwal** [comment]
Working in https://github.com/gdg-x/aura-admin/tree/dev-2021

**Comment by vrijraj** [comment]
Fixed in v3.5.0
