### ISSUE TITLE
Getting Started [Add Initial User]

### ISSUE THREAD

**Issue by kartikderasari** [gdg-x/aura-admin#76]
### Getting Started Module

Earlier the Initial User was added using [Getting Started](https://github.com/gdg-x/aura-admin#getting-started) - 19. Cloud Functions. But now as we are pulling out Cloud Functions from Aura Admin, we might need to find an alternative solution to add an Initial User.

- [ ] Add Initial User Alternative Solution
- [ ] Update [Getting Started](https://github.com/gdg-x/aura-admin#getting-started) and [Full Documentation](https://docs.google.com/document/d/1WhpMxCE-H47em73F-8pcNGETye5Qun8cY3Jdg7jx6DE/edit?usp=sharing)

**Comment by bharatagsrwal** [comment]
Hey @kartikderasari, I think you misunderstood, Aura does not call any cloud function for initial user,
![image](https://user-images.githubusercontent.com/43988371/112844951-eb8e6e00-90c1-11eb-8028-9804615b3ba6.png)
this one is for setting up the emails, which were sent by function to users.

For updating the docs, we haven't changed anything for stable version, all the features in branch `dev-2021` are in testing phase. as we introduced a new version of user management without cloud functions and that is in testing phase, until new version of user management does not get released, all the procedure to setup is same as per mentioned in docs.
